In [1]:
%reload_ext autoreload
%autoreload 2

In [21]:
!pip install pandas

1339.33s - pydevd: Sending message related to process being replaced timed-out after 5 seconds



[notice] A new release of pip is available: 26.1.2 -> 26.2.1
[notice] To update, run: pip install --upgrade pip


In [22]:
import numpy as np
from sklearn.datasets import make_classification
from sklearn.linear_model import LogisticRegression
from mapie.risk_control import MultiClassificationController
from mapie.risk_control.methods import ltt_procedure
from mapie.utils import check_valid_ltt_params_index
from sklearn.metrics import average_precision_score
#import plotly.express as px
#import plotly.graph_objects as go

X_toy, y_toy = make_classification(
            n_samples=300,
            n_features=5,
            n_informative=5,
            n_redundant=0,
            n_repeated=0,
            n_classes=4,
            n_clusters_per_class=1,
            #weights=[0.5, 0.5],
            flip_y=0,
            random_state=42
        )
#X_toy, y_toy = make_gaussian_quantiles(
#            n_samples=1000,
#            n_features=2,
#           n_classes=5,
#            #weights=[0.5, 0.5],
#        )

In [3]:
lr = LogisticRegression()
clf = LogisticRegression().fit(X_toy, y_toy)

In [23]:
y_train_pred = clf.predict_proba(X_toy)
print(average_precision_score(y_toy,y_train_pred))
clf

0.8966181862875122


,"penalty penalty: {'l1', 'l2', 'elasticnet', None}, default='l2'Specify the norm of the penalty:- `None`: no penalty is added;- `'l2'`: add an L2 penalty term and it is the default choice;- `'l1'`: add an L1 penalty term;- `'elasticnet'`: both L1 and L2 penalty terms are added... warning:: Some penalties may not work with some solvers. See the parameter `solver` below, to know the compatibility between the penalty and solver... versionadded:: 0.19 l1 penalty with SAGA solver (allowing 'multinomial' + L1).. deprecated:: 1.8 `penalty` was deprecated in version 1.8 and will be removed in 1.10. Use `l1_ratio` and `C` instead. `l1_ratio=0` for `penalty='l2'`, `l1_ratio=1` for `penalty='l1'`, `l1_ratio` set to any float between 0 and 1 for `penalty='elasticnet'`, and `C=np.inf` for `penalty=None`.",'deprecated'
,"C C: float, default=1.0Inverse of regularization strength; must be a positive float.Like in support vector machines, smaller values specify strongerregularization. `C=np.inf` results in unpenalized logistic regression.For a visual example on the effect of tuning the `C` parameterwith an L1 penalty, see::ref:`sphx_glr_auto_examples_linear_model_plot_logistic_path.py`.",1.0
,"l1_ratio l1_ratio: float, default=0.0The Elastic-Net mixing parameter, with `0 <= l1_ratio <= 1`. Setting`l1_ratio=1` gives a pure L1-penalty, setting `l1_ratio=0` a pure L2-penalty.Any value between 0 and 1 gives an Elastic-Net penalty of the form`l1_ratio * L1 + (1 - l1_ratio) * L2`... warning:: Certain values of `l1_ratio`, i.e. some penalties, may not work with some solvers. See the parameter `solver` below, to know the compatibility between the penalty and solver... versionchanged:: 1.8 Default value changed from None to 0.0... deprecated:: 1.8 `None` is deprecated and will be removed in version 1.10. Always use `l1_ratio` to specify the penalty type.",0.0
,"dual dual: bool, default=FalseDual (constrained) or primal (regularized, see also:ref:`this equation <regularized-logistic-loss>`) formulation. Dual formulationis only implemented for l2 penalty with liblinear solver. Prefer `dual=False`when n_samples > n_features.",False
,"tol tol: float, default=1e-4Tolerance for stopping criteria.",0.0001
,"fit_intercept fit_intercept: bool, default=TrueSpecifies if a constant (a.k.a. bias or intercept) should beadded to the decision function.",True
,"intercept_scaling intercept_scaling: float, default=1Useful only when the solver `liblinear` is usedand `self.fit_intercept` is set to `True`. In this case, `x` becomes`[x, self.intercept_scaling]`,i.e. a ""synthetic"" feature with constant value equal to`intercept_scaling` is appended to the instance vector.The intercept becomes``intercept_scaling * synthetic_feature_weight``... note:: The synthetic feature weight is subject to L1 or L2 regularization as all other features. To lessen the effect of regularization on synthetic feature weight (and therefore on the intercept) `intercept_scaling` has to be increased.",1
,"class_weight class_weight: dict or 'balanced', default=NoneWeights associated with classes in the form ``{class_label: weight}``.If not given, all classes are supposed to have weight one.The ""balanced"" mode uses the values of y to automatically adjustweights inversely proportional to class frequencies in the input dataas ``n_samples / (n_classes * np.bincount(y))``.Note that these weights will be multiplied with sample_weight (passedthrough the fit method) if sample_weight is specified... versionadded:: 0.17 *class_weight='balanced'*",None
,"random_state random_state: int, RandomState instance, default=NoneOnly used for `solver` == 'sag', 'saga' or 'liblinear' to shuffle thedata. It has no effect on the other solvers.See :term:`Glossary <random_state>` for details.",None
,"solver solver: {'lbfgs', 'liblinear', 'newton-cg', 'newton-cholesky', 'sag', 'saga'}, default='lbfgs'Algorithm to use in the optimization problem. Default is 'lbfgs'.To choose a solver, you might want to consider the following

In [5]:
# regarder avec la valeur des p values. 

In [24]:
def funct_risk_combination_selector(input):
    output = input[1,:]
    return output 

In [25]:
np.linspace(0.9, 0.05, 10)

array([0.9       , 0.80555556, 0.71111111, 0.61666667, 0.52222222,
       0.42777778, 0.33333333, 0.23888889, 0.14444444, 0.05      ])

In [26]:
from mapie.risk_control.risks import build_precision_ovr

In [27]:
build_precision_ovr(np.unique(y_toy))

In [10]:
mapie_clf = MultiClassificationController(predict_function=clf.predict_proba, target_level=0.75,risks=build_precision_ovr(np.unique(y_toy)),
                                          confidence_level = 0.9,list_predict_params=np.linspace(0.05, 0.9, 10),
                                          fwer_method="split_fixed_sequence",
                                          risk_combination_method=1)#
#mapie_clf.calibrate(X_toy, y_toy)

In [11]:
y_calibrate = y_toy
X_calibrate = X_toy

In [12]:
mapie_clf.learn_fixed_sequence_order(X_calibrate,y_calibrate)

In [13]:
mapie_clf.calibrate(X_toy, y_toy)

/Users/trezel/Documents/code/MAPIE/mapie/utils.py:1398: UserWarning: All provided predict_params control the risk at the given target and confidence levels. You may want to use more difficult target levels.
  warnings.warn(


In [18]:
y_calibrate_ = np.asarray(y_calibrate, dtype=int)
mapie_clf.risk_combination_method = mapie_clf._check_risk_combination_method(
    mapie_clf.risk_combination_method, y_calibrate
)
original_params = mapie_clf._predict_params
if mapie_clf.fwer_method == "split_fixed_sequence":
    if mapie_clf._learned_fixed_sequence is None:
        raise ValueError(
            "You must call 'learn_fixed_sequence_order' before 'calibrate' "
            "when using fwer_method='split_fixed_sequence'."
        )
    mapie_clf._predict_params = mapie_clf._learned_fixed_sequence

predictions_per_param = mapie_clf._get_predictions_per_param(
    X_calibrate, mapie_clf._predict_params, is_calibration_step=True
)
# populate multirisks
class_labels = np.unique(y_calibrate)
#[risk.populate_risk_per_class(class_labels) for risk in mapie_clf._risk]
# broadcast one _alpha_level per class.


In [19]:
predictions_per_param

array([[2., 1., 1., 1., 2., 0., 3., 2., 2., 3., 3., 1., 0., 0., 1., 0.,
        2., 0., 1., 2., 0., 3., 1., 1., 3., 2., 3., 3., 2., 2., 3., 1.,
        2., 1., 1., 3., 1., 2., 0., 2., 1., 2., 2., 1., 0., 2., 2., 3.,
        0., 2., 1., 3., 2., 3., 3., 3., 0., 2., 0., 0., 3., 0., 3., 0.,
        2., 2., 0., 0., 2., 1., 2., 1., 0., 0., 3., 0., 0., 0., 1., 2.,
        1., 1., 0., 3., 0., 3., 1., 0., 3., 3., 2., 3., 3., 0., 1., 2.,
        2., 3., 2., 0., 2., 3., 0., 2., 1., 2., 0., 1., 3., 0., 1., 1.,
        0., 2., 3., 3., 0., 3., 3., 1., 1., 1., 2., 3., 1., 3., 3., 0.,
        3., 2., 2., 3., 2., 2., 2., 1., 1., 1., 0., 1., 3., 2., 3., 0.,
        0., 0., 0., 2., 3., 1., 1., 3., 0., 0., 2., 1., 2., 3., 1., 3.,
        3., 1., 0., 0., 0., 2., 2., 0., 2., 0., 1., 3., 0., 2., 3., 1.,
        2., 3., 0., 0., 2., 3., 0., 1., 1., 0., 3., 3., 1., 2., 2., 0.,
        1., 0., 1., 2., 2., 1., 0., 1., 3., 2., 1., 3., 0., 3., 0., 0.,
        3., 1., 3., 2., 3., 1., 0., 3., 2., 0., 3., 1., 1., 0., 

In [13]:
# non classe => nan car classe 0 existe déjà. 
predictions_per_param.shape

(7, 300)

In [14]:
risk_values, eff_sample_sizes = mapie_clf._get_risk_values_and_eff_sample_sizes(
    y_calibrate_, predictions_per_param, mapie_clf._risk
)

In [15]:
(valid_index, p_values) = ltt_procedure(
            risk_values,
            np.expand_dims(mapie_clf._alpha, axis=1),
            mapie_clf._delta,
            eff_sample_sizes,
            binary = True,
            fwer_method=mapie_clf.fwer_method,
        )

In [16]:
p_values

array([[0.00380332],
       [0.01542183],
       [0.00704623],
       [0.15505899],
       [0.17766264],
       [0.03219198],
       [0.05513557]])

In [17]:

fig = px.line(p_values, title='plot of an array  : y=p_values , x = index')

n_lambdas = p_values.shape[0]
for j, list_index in enumerate(valid_index):
    colors = []
    for index in range(n_lambdas):
        if index in list_index:
            colors.append("green")
        else:
            colors.append("red")
    fig.add_trace(go.Scatter(
        x=list(range(n_lambdas)),
        y=p_values[:, j],
        mode="markers",
        marker=dict(color=colors),
        showlegend=False,
    ))

fig.show()

In [ ]:
x